CREATE TABLE user (
    UserId INT PRIMARY KEY AUTO_INCREMENT,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Bio NVARCHAR(500),
    Username VARCHAR(50) UNIQUE NOT NULL,
    ProfilePic VARCHAR(255),
    Followers INT DEFAULT 0,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE post (
    PostId INT PRIMARY KEY AUTO_INCREMENT,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    Views INT DEFAULT 0,
    Likes INT DEFAULT 0,
    UserId INT,
    Caption NVARCHAR(500),
    Picture VARCHAR(255),
    FOREIGN KEY (UserId) REFERENCES user(UserId) ON DELETE CASCADE
);

CREATE TABLE comment (
    CommentId INT PRIMARY KEY AUTO_INCREMENT,
    PostId INT,
    UserId INT,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PostId) REFERENCES post(PostId) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES user(UserId) ON DELETE CASCADE
);

CREATE TABLE following (
    FollowingId INT PRIMARY KEY AUTO_INCREMENT,
    FollowerId INT,
    FolloweeId INT,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FollowerId) REFERENCES user(UserId) ON DELETE CASCADE,
    FOREIGN KEY (FolloweeId) REFERENCES user(UserId) ON DELETE CASCADE,
    CONSTRAINT unique_follow UNIQUE (FollowerId, FolloweeId)
);

CREATE TABLE story (
    StoryId INT PRIMARY KEY AUTO_INCREMENT,
    Views INT DEFAULT 0,
    UserId INT,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    ExpirationTime DATETIME GENERATED ALWAYS AS (Timestamp + INTERVAL 1 DAY) VIRTUAL,
    FOREIGN KEY (UserId) REFERENCES user(UserId) ON DELETE CASCADE
);

CREATE TABLE DM (
    DMId INT PRIMARY KEY AUTO_INCREMENT,
    SenderId INT,
    RecipientId INT,
    Message NVARCHAR(1000) NOT NULL,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SenderId) REFERENCES user(UserId) ON DELETE CASCADE,
    FOREIGN KEY (RecipientId) REFERENCES user(UserId) ON DELETE CASCADE
);

CREATE TABLE likes (
    LikeId INT PRIMARY KEY AUTO_INCREMENT,
    UserId INT,
    PostId INT,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES user(UserId) ON DELETE CASCADE,
    FOREIGN KEY (PostId) REFERENCES post(PostId) ON DELETE CASCADE,
    CONSTRAINT unique_like UNIQUE (UserId, PostId)
);
